#!/usr/bin/env python3
"""
Catalog data-quality auditor.

Runs the full 12-category cross-check against the catalog sources
(YAML entities + benchmarks.jsonl) and exits non-zero if any issue is
found. Designed for CI: fast, deterministic, no network calls, clear
output.

Categories:
  1. Duplicate IDs (models, artifacts, benchmarks.jsonl, terms)
  2. Cross-reference integrity (artifact_ref, model_id, source IDs)
  3. Upstream applies_to validity
  4. Hugging Face URL consistency
  5. Zero unknown fields (precision, quantization, runtime flags, etc)
  6. Officiality logic (source_group ↔ apple_export_recipe)
  7. Term relation integrity
  8. Metadata count accuracy
  9. Date format validation + capability ↔ modality sanity
 10. License ↔ upstream consistency (permissive claims over restricted
     upstreams; unverified upstreams must not claim permissive terms)
 11. Retired-store guard (benchmarks.yaml must not reappear — JSONL is the
     single benchmark source of truth)
 12. Typosquat / confusable IDs (NFKC + confusable skeletons, edit-distance
     near-misses across different artifact owners, reserved apple-*
     namespace, alias collisions with foreign model IDs)
"""
from __future__ import annotations

import json
import re
import sys
import unicodedata
from collections import Counter
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]

#: Upstream license_terms values that are incompatible with a model claiming
#: a permissive license + likely commercial use.
NON_PERMISSIVE_LICENSE_TERMS = {"restricted", "review_required"}

#: model.source_group → artifact.group pairings allowed beyond identity.
#: The artifact group enum (schema/artifact.schema.json) has no 'fabric';
#: coreai-fabric conversions are independent/external artifacts, so a
#: fabric model pairs with an external artifact (the same mapping applied
#: by coreai_catalog/contribute.py build_artifact_entry and by
#: coreai-fabric's register command).
ALLOWED_GROUP_PAIRINGS = {"fabric": {"external"}}


def group_pairing_ok(source_group: str, artifact_group: str) -> bool:
    """True when a model's source_group may pair with an artifact's group."""
    if artifact_group == source_group:
        return True
    return artifact_group in ALLOWED_GROUP_PAIRINGS.get(source_group, set())


def read_yaml(path: Path) -> dict:
    return yaml.safe_load(path.read_text()) or {}


# ── Category 12 helpers: typosquat / confusable ID detection ──

#: Single-character confusables mapped to their ASCII skeleton, restricted
#: to the charset relevant for catalog IDs (lowercase latin + digits +
#: separators). Sourced from Unicode TR39 confusables.txt entries for
#: Cyrillic/Greek lookalikes of [a-z0-9]; NFKC already folds fullwidth
#: and other compatibility forms before this map is applied.
CONFUSABLES = {
    # Cyrillic → Latin
    "а": "a", "в": "b", "с": "c", "е": "e", "ѕ": "s", "і": "i", "ј": "j",
    "к": "k", "м": "m", "н": "h", "о": "o", "р": "p", "т": "t", "у": "y",
    "х": "x", "ԁ": "d", "ɡ": "g", "ԛ": "q", "ԝ": "w", "г": "r", "ь": "b",
    "п": "n", "и": "u", "л": "n", "ф": "o",
    # Greek → Latin
    "α": "a", "β": "b", "γ": "y", "ε": "e", "η": "n", "ι": "i", "κ": "k",
    "ν": "v", "ο": "o", "ρ": "p", "τ": "t", "υ": "u", "χ": "x", "ω": "w",
    "σ": "o", "μ": "u",
    # Digit lookalikes
    "０": "0", "１": "1", "ⅼ": "l", "𝟎": "0", "𝟏": "1",
}


def id_skeleton(value: str) -> str:
    """Confusable skeleton of an ID: NFKC + casefold + confusable map +
    strip combining marks + collapse separators (-, _, ., whitespace).

    Two IDs with equal skeletons differ only by case, hyphenation,
    compatibility forms, or lookalike characters — i.e. one can be
    visually mistaken for the other by humans and agents.
    """
    s = unicodedata.normalize("NFKC", value).casefold()
    s = "".join(CONFUSABLES.get(c, c) for c in s)
    s = "".join(c for c in s if not unicodedata.combining(c))
    return re.sub(r"[-_.\s]+", "", s)


def edit_distance(a: str, b: str, limit: int = 3) -> int:
    """Levenshtein distance, short-circuiting above *limit*."""
    if abs(len(a) - len(b)) > limit:
        return limit + 1
    prev = list(range(len(b) + 1))
    for i, ca in enumerate(a, 1):
        cur = [i]
        for j, cb in enumerate(b, 1):
            cur.append(min(prev[j] + 1, cur[j - 1] + 1,
                           prev[j - 1] + (ca != cb)))
        if min(cur) > limit:
            return limit + 1
        prev = cur
    return prev[-1]


def read_aliases(path: Path) -> dict[str, list[str]]:
    """Alias map from dist/aliases.json (generated by
    coreai_catalog/exports.py export_aliases from artifacts.yaml HF repo
    names, model source_path segments, and ID format variants; kept in
    sync with the YAML sources by the CI `git diff dist/` gate).
    Missing file → empty map (audit stays offline-safe)."""
    if not path.exists():
        return {}
    data = json.loads(path.read_text())
    return data.get("aliases", {}) or {}


def typosquat_issues(
    models: list[dict],
    artifacts: list[dict],
    aliases: dict[str, list[str]] | None = None,
) -> list[str]:
    """Category 12: typosquat / confusable / reserved-namespace checks.

    a) Confusable collision — two distinct model/artifact IDs sharing a
       skeleton (differ only by case / hyphenation / lookalike chars).
    b) Squat signal — two model IDs within edit distance 1-2 whose
       artifacts point at DIFFERENT Hugging Face owners. Same-owner
       near-IDs (size/version ladders like qwen3-vl-2b/4b/8b) are the
       normal case and stay unflagged.
    c) Reserved namespace — `apple-*` IDs require source_group official
       (models) / group official (artifacts): nobody may squat the
       vendor's name.
    d) Alias hijack — an alias of model X whose skeleton equals the ID
       of a different model Y (aliases legitimately collide with each
       other via shared HF repos/source docs, so only alias→foreign-ID
       collisions are flagged).
    """
    issues: list[str] = []
    aliases = aliases or {}
    art_by_id = {a["id"]: a for a in artifacts}

    def hf_owner(model: dict) -> str | None:
        art = art_by_id.get(model.get("artifact_ref")) or {}
        return (art.get("huggingface") or {}).get("owner")

    # a) Confusable skeleton collisions across all model + artifact IDs.
    skeleton_map: dict[str, set[str]] = {}
    for entity_id in [m["id"] for m in models] + [a["id"] for a in artifacts]:
        skeleton_map.setdefault(id_skeleton(entity_id), set()).add(entity_id)
    for skel, id_set in sorted(skeleton_map.items()):
        if len(id_set) > 1:
            issues.append(
                f"confusable IDs {sorted(id_set)} share skeleton '{skel}' "
                "(differ only by case/hyphenation/lookalike characters)"
            )

    # b) Edit-distance 1-2 model IDs owned by different HF accounts.
    model_list = sorted(models, key=lambda m: m["id"])
    for i, m1 in enumerate(model_list):
        for m2 in model_list[i + 1:]:
            dist = edit_distance(m1["id"], m2["id"], limit=2)
            if 1 <= dist <= 2:
                o1, o2 = hf_owner(m1), hf_owner(m2)
                if o1 != o2:
                    issues.append(
                        f"model IDs '{m1['id']}' (hf owner {o1}) and "
                        f"'{m2['id']}' (hf owner {o2}) are within edit "
                        f"distance {dist} but have different artifact "
                        "owners — possible typosquat"
                    )

    # c) Reserved namespace: apple-* requires official provenance. The
    #    check runs on the confusable-folded form (separators preserved)
    #    so 'аpple-x' (Cyrillic а) cannot dodge it.
    def _is_reserved(entity_id: str) -> bool:
        norm = unicodedata.normalize("NFKC", entity_id).casefold()
        norm = "".join(CONFUSABLES.get(c, c) for c in norm)
        return bool(re.match(r"apple[-_.]", norm))

    for m in models:
        if _is_reserved(m["id"]) and m.get("source_group") != "official":
            issues.append(
                f"model {m['id']} uses the reserved 'apple-' namespace "
                f"but source_group={m.get('source_group')} "
                "(reserved for source_group: official)"
            )
    for a in artifacts:
        if _is_reserved(a["id"]) and a.get("group") != "official":
            issues.append(
                f"artifact {a['id']} uses the reserved 'apple-' namespace "
                f"but group={a.get('group')} (reserved for group: official)"
            )

    # d) Alias of model X colliding with the ID of a different model Y.
    id_by_skeleton: dict[str, set[str]] = {}
    for m in models:
        id_by_skeleton.setdefault(id_skeleton(m["id"]), set()).add(m["id"])
    for model_id, alias_list in sorted(aliases.items()):
        for alias in alias_list:
            for other in sorted(id_by_skeleton.get(id_skeleton(alias), set())):
                if other != model_id:
                    issues.append(
                        f"alias '{alias}' of model {model_id} is confusable "
                        f"with the ID of a different model '{other}'"
                    )
    return issues


def read_benchmarks_jsonl(path: Path) -> list[dict]:
    """Read benchmarks.jsonl (single benchmark source of truth)."""
    benchmarks: list[dict] = []
    if not path.exists():
        return benchmarks
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        benchmarks.append(json.loads(line))
    return benchmarks


def main() -> int:
    catalog = read_yaml(ROOT / "catalog.yaml")
    artifacts_data = read_yaml(ROOT / "artifacts.yaml")
    terms_data = read_yaml(ROOT / "terms.yaml")
    upstreams_data = read_yaml(ROOT / "upstreams.yaml")
    sources_data = read_yaml(ROOT / "sources.yaml")

    models = catalog.get("models", [])
    artifacts = artifacts_data.get("artifacts", [])
    benchmarks = read_benchmarks_jsonl(ROOT / "benchmarks.jsonl")
    terms = terms_data.get("terms", [])
    sources = sources_data.get("sources", [])

    issues: list[str] = []

    # ── 1. Duplicate IDs ──
    for items, label in [
        (models, "model"),
        (artifacts, "artifact"),
        (benchmarks, "benchmark"),
        (terms, "term"),
    ]:
        ids = [i["id"] for i in items]
        dups = [x for x, c in Counter(ids).items() if c > 1]
        if dups:
            issues.append(f"Duplicate {label} IDs: {dups}")

    # ── 2. Cross-reference integrity ──
    model_ids = {m["id"] for m in models}
    art_by_id = {a["id"]: a for a in artifacts}
    src_ids = {s["id"] for s in sources}

    UPSTREAM_GROUPS = [
        "framework_sources",
        "conversion_sources",
        "artifact_hosts",
        "benchmark_sources",
        "sample_sources",
        "original_model_sources",
        "license_sources",
    ]
    all_upstreams: list[dict] = []
    for g in UPSTREAM_GROUPS:
        all_upstreams.extend(upstreams_data.get(g, []) or [])
    up_ids = {u["id"] for u in all_upstreams}

    for m in models:
        ref = m.get("artifact_ref")
        if ref not in art_by_id:
            issues.append(f"model {m['id']} → missing artifact_ref '{ref}'")
        elif not group_pairing_ok(m["source_group"], art_by_id[ref].get("group")):
            issues.append(
                f"model {m['id']} source_group={m['source_group']} "
                f"vs artifact group={art_by_id[ref].get('group')}"
            )
        for s in m.get("sources", []):
            if s not in src_ids and s not in up_ids:
                issues.append(f"model {m['id']} → missing source '{s}'")

    for b in benchmarks:
        if b["model_id"] not in model_ids:
            issues.append(f"benchmark {b['id']} → missing model_id '{b['model_id']}'")
        if b["source"] not in src_ids and b["source"] not in up_ids:
            issues.append(f"benchmark {b['id']} → missing source '{b['source']}'")

    # ── 3. Upstream applies_to ──
    for u in upstreams_data.get("original_model_sources", []) or []:
        for t in u.get("applies_to", []) or []:
            if t not in model_ids:
                issues.append(
                    f"upstream {u['id']} applies_to '{t}' → not a known model ID"
                )

    # ── 4. HF URL consistency ──
    for a in artifacts:
        hf = a.get("huggingface", {}) or {}
        url = hf.get("url", "")
        owner = hf.get("owner", "")
        repo = hf.get("repo", "")
        path = hf.get("path")
        expected = f"https://huggingface.co/{owner}/{repo}"
        if path:
            expected = f"{expected}/{path}"
        if url and url != expected:
            issues.append(
                f"artifact {a['id']} URL mismatch: '{url}' != '{expected}'"
            )

    # ── 5. Zero unknown fields ──
    critical_fields = [
        ("size", "precision"),
        ("size", "quantization"),
        ("size", "artifact_size"),
        ("runtime", "stock_runtime"),
        ("runtime", "custom_kernel"),
        ("runtime", "patch_required"),
        ("runtime", "aot_required"),
    ]
    for m in models:
        for section, field in critical_fields:
            val = m.get(section, {}).get(field)
            if val == "unknown":
                issues.append(
                    f"model {m['id']} has unknown: {section}.{field} "
                    "(extract from upstream card or mark 'not_published')"
                )

    # ── 6. Officiality logic ──
    for m in models:
        a = art_by_id.get(m.get("artifact_ref"))
        if a:
            off = a.get("officiality", {}) or {}
            if m["source_group"] == "official" and not off.get("apple_export_recipe"):
                issues.append(
                    f"model {m['id']} is official but apple_export_recipe=False"
                )
            if m["source_group"] == "zoo" and off.get("apple_export_recipe"):
                issues.append(
                    f"model {m['id']} is zoo but apple_export_recipe=True"
                )
            if m["source_group"] == "fabric" and off.get("apple_export_recipe"):
                issues.append(
                    f"model {m['id']} is fabric but apple_export_recipe=True"
                )
            if off.get("apple_hosted_artifact"):
                issues.append(
                    f"artifact {a['id']} claims apple_hosted_artifact=True "
                    "(all current entries should be False)"
                )

    # ── 7. Term relation integrity ──
    term_ids = {t["id"] for t in terms}
    for t in terms:
        for rel in t.get("relations", []) or []:
            parts = rel.split(":")
            if len(parts) != 2:
                issues.append(f"term {t['id']} malformed relation '{rel}'")
                continue
            target = parts[1]
            if target not in term_ids:
                issues.append(
                    f"term {t['id']} relation → '{target}' is not a known term"
                )

    # ── 8. Metadata count accuracy ──
    # (benchmarks.jsonl carries no metadata block — nothing to cross-check)
    for fname, data_key in [("artifacts", "artifacts")]:
        data = read_yaml(ROOT / f"{fname}.yaml")
        meta_count = data.get("metadata", {}).get("count")
        actual = len(data.get(data_key, []))
        if meta_count is not None and meta_count != actual:
            issues.append(
                f"{fname}.yaml metadata.count={meta_count} but actual={actual}"
            )

    # ── 9. Date format + capability ↔ modality sanity ──
    date_re = re.compile(r"^\d{4}-\d{2}-\d{2}$")
    for m in models:
        lv = m.get("last_verified", "")
        if lv and not date_re.match(lv):
            issues.append(f"model {m['id']} bad date '{lv}'")
        caps = set(m.get("capabilities", []))
        inp = set(m.get("modalities", {}).get("input", []))
        out = set(m.get("modalities", {}).get("output", []))
        vision_caps = {
            "vision-language", "object-detection", "instance-segmentation",
            "promptable-segmentation", "monocular-depth", "super-resolution",
            "document-ocr", "visual-document-retrieval", "image-to-3d",
            "image-text-similarity", "gui-grounding",
        }
        if caps & vision_caps and "image" not in inp:
            issues.append(f"model {m['id']} has vision capability but no image input")
        if "text-to-speech" in caps and "audio" not in out:
            issues.append(f"model {m['id']} is TTS but no audio output")
        if "text-to-video" in caps and "video" not in out:
            issues.append(f"model {m['id']} is text-to-video but no video output")

    for b in benchmarks:
        obs = b.get("observed_date", "")
        if not obs:
            issues.append(f"benchmark {b['id']} missing observed_date")
        elif not date_re.match(obs):
            issues.append(f"benchmark {b['id']} bad date '{obs}'")

    # ── 10. License ↔ upstream consistency ──
    # Join each model to its original_model_sources upstream(s) via
    # applies_to and compare the model's declared license posture with
    # the upstream's license_terms. A model must not claim likely
    # commercial use while its upstream license family is restricted or
    # review_required (license laundering guard).
    model_to_upstreams: dict[str, list[dict]] = {}
    owner_to_upstreams: dict[str, list[dict]] = {}
    for u in upstreams_data.get("original_model_sources", []) or []:
        for t in u.get("applies_to", []) or []:
            model_to_upstreams.setdefault(t, []).append(u)
        if u.get("owner"):
            owner_to_upstreams.setdefault(u["owner"].lower(), []).append(u)
        # An upstream whose identity is itself unverified cannot ground a
        # 'permissive' license claim (schema rule: license_terms must be
        # grounded in verified license strings; conservative default is
        # review_required).
        if (
            u.get("license_terms") == "permissive"
            and (u.get("trust") == "needs_review" or u.get("owner") == "unknown")
        ):
            issues.append(
                f"upstream {u['id']} has trust={u.get('trust')} / "
                f"owner={u.get('owner')} but license_terms=permissive — "
                "unverified upstreams must stay review_required until the "
                "upstream identity and license are verified"
            )

    # Fabric-registered models (and any model carrying upstream_repo) are not
    # listed in an upstream's applies_to at register time, so they would bypass
    # the laundering guard. Join them to the matching upstream by owner
    # (upstream_repo 'google/gemma-4-12B' -> owner 'google'), but ONLY when a
    # distinguishing family token from the upstream id also appears in the repo
    # — one owner can ship models under different licenses (facebook owns both
    # SAM=review_required and V-JEPA2=MIT), so owner alone would false-match.
    for m in models:
        repo = m.get("upstream_repo")
        if not (repo and "/" in repo) or model_to_upstreams.get(m["id"]):
            continue
        owner, _, name = repo.partition("/")
        repo_l = repo.lower()
        for u in owner_to_upstreams.get(owner.lower(), []):
            # Family tokens = the upstream id's segments minus the owner prefix
            # (e.g. 'google-gemma' -> 'gemma'; 'meta-sam' -> 'sam').
            tokens = [seg for seg in u["id"].lower().split("-")
                      if seg and seg != owner.lower() and len(seg) >= 3]
            if any(tok in repo_l for tok in tokens):
                model_to_upstreams.setdefault(m["id"], []).append(u)

    for m in models:
        commercial_use = m.get("license", {}).get("commercial_use")
        for u in model_to_upstreams.get(m["id"], []):
            terms_val = u.get("license_terms")
            if commercial_use == "likely" and terms_val in NON_PERMISSIVE_LICENSE_TERMS:
                issues.append(
                    f"model {m['id']} claims commercial_use=likely "
                    f"(license '{m.get('license', {}).get('name')}') but upstream "
                    f"{u['id']} has license_terms={terms_val} — "
                    "set commercial_use: check_license or fix the upstream record"
                )

    # ── 11. Retired-store guard ──
    # benchmarks.jsonl is the single benchmark source of truth. The legacy
    # YAML store was retired; if it reappears, exports/docs/audits would
    # silently drift apart again.
    for retired in (ROOT / "benchmarks.yaml",
                    ROOT / "coreai_catalog" / "data" / "benchmarks.yaml"):
        if retired.exists():
            issues.append(
                f"{retired.relative_to(ROOT)} exists but is retired — "
                "benchmarks.jsonl is the single benchmark store; delete the YAML file"
            )
    if not (ROOT / "benchmarks.jsonl").exists():
        issues.append("benchmarks.jsonl is missing (single benchmark source of truth)")

    # ── 12. Typosquat / confusable IDs ──
    issues.extend(
        typosquat_issues(
            models, artifacts, read_aliases(ROOT / "dist" / "aliases.json")
        )
    )

    # ── Output ──
    if issues:
        print(f"\n❌ {len(issues)} issue(s) found:\n")
        for issue in sorted(issues):
            print(f"  {issue}")
        print(f"\nTotal: {len(issues)} issue(s)")
        return 1

    print(
        f"OK: 0 issues across {len(models)} models, {len(artifacts)} artifacts, "
        f"{len(benchmarks)} benchmarks, {len(terms)} terms, {len(all_upstreams)} upstreams."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
